Repository SU-SWS/stanford_events, pull requests merged in 2020-06, with the labels that each got.

#3 Create label.yml
  .github/workflows/label.yml
Labels: size/xs

#4 D8CORE-000: Events Updates
  modules/stanford_events_importer/config/install/migrate_plus.migration.stanford_events_importer.yml
Labels: size/xs

#5 Events, Series, and Importer Tests
  config/install/views.view.stanford_events.yml
  config/install/views.view.stanford_events_past.yml
  content/taxonomy_term/80a4d81e-8eff-4138-8529-5bff4f7952c1.json
  content/taxonomy_term/f9979993-225b-4bdb-906f-daa2626332c5.json
  modules/stanford_events_importer/config/install/core.entity_form_display.config_pages.stanford_events_importer.default.yml
  modules/stanford_events_importer/config/install/field.field.config_pages.stanford_events_importer.su_event_xml_url.yml
  modules/stanford_events_importer/config/install/migrate_plus.migration.stanford_events_importer.yml
  modules/stanford_events_importer/src/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidget.php
  modules/stanford_events_importer/src/StanfordEventsImporter.php
  modules/stanford_events_importer/stanford_events_importer.module
  modules/stanford_events_importer/tests/src/Kernel/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidgetTest.php
  modules/stanford_events_importer/tests/src/Unit/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidgetTest.php
  modules/stanford_events_importer/tests/src/Unit/StanfordEventsImporterTest.php
  tests/codeception/acceptance/StanfordEventsCest.php
  tests/codeception/acceptance/StanfordEventsSeriesCest.php
Labels: size/s

#6 Update core.entity_view_display.node.stanford_event.default.yml
  config/install/core.entity_view_display.node.stanford_event.default.yml
Labels: size/xs

#7 Fix missing event title in views and re-ordered event node fields
  config/install/core.entity_view_display.node.stanford_event.default.yml
  config/install/views.view.stanford_events.yml
Labels: size/m

#9 D8CORE-2265: adding styles for past events scroll button
  dist/css/stanford_events.views.css
  lib/scss/stanford_events.views.scss
Labels: size/xs

#11 D8CORE-2070: increasing and making MS margin consistent for accelerant headers
  dist/css/stanford_events.event-list.css
  lib/scss/components/event-list/stanford_events.event-list.scss
Labels: size/xs
