Repository SU-SWS/stanford_events, pull requests merged in 2020-11, with the labels that each got.

#36 D8CORE-2930 D8CORE-2924: fixing the event card display and removing duplicate code
  dist/css/stanford_events.event-card.css
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-card/stanford_events.event-card.scss
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.views.scss
  templates/components/events-card/events-card.html.twig
  templates/components/events-card/events-card.ui_patterns.yml
  templates/components/events-list/events-list.html.twig
Labels: size/s

#32 D8CORE-2873: Adding the Past label
  config/install/core.entity_view_display.node.stanford_event.default.yml
  dist/css/stanford_events.node.css
  dist/js/stanford_events.node.behaviors.js
  lib/js/stanford_events.behavior.js
  lib/scss/stanford_events.node.scss
  stanford_events.libraries.yml
  stanford_events.module
Labels: size/xs

#35 D8CORE-2306: removed sorting controls in the event schedule entity reference field.
  stanford_events.module
Labels: size/xs

#39 D8CORE-2873-v2: fixing the date format
  dist/js/stanford_events.node.behaviors.js
  lib/js/stanford_events.behavior.js
Labels: size/xs

#42 Update tests for D9 phpunit
  modules/stanford_events_importer/tests/src/Unit/StanfordEventsImporterTest.php
Labels: size/xs

#43 Updated default content module
  composer.json
  content/menu_link_content/d91b714a-4609-41c5-a9c4-d8140ed3a764.json
  content/menu_link_content/d91b714a-4609-41c5-a9c4-d8140ed3a764.yml
  content/taxonomy_term/6a2ade62-d0bf-4f21-be92-fb5ad9a0bde0.json
  content/taxonomy_term/6a2ade62-d0bf-4f21-be92-fb5ad9a0bde0.yml
  content/taxonomy_term/6eaf9909-9f26-4e01-9121-34ecb577f0e0.json
  content/taxonomy_term/6eaf9909-9f26-4e01-9121-34ecb577f0e0.yml
  content/taxonomy_term/80a4d81e-8eff-4138-8529-5bff4f7952c1.json
  content/taxonomy_term/80a4d81e-8eff-4138-8529-5bff4f7952c1.yml
  content/taxonomy_term/913f780a-62d6-4371-b8c4-ad39210bf80c.json
  content/taxonomy_term/913f780a-62d6-4371-b8c4-ad39210bf80c.yml
  content/taxonomy_term/bb117bce-7413-4214-9e89-a831d5e8f69c.json
  content/taxonomy_term/bb117bce-7413-4214-9e89-a831d5e8f69c.yml
  content/taxonomy_term/e6f319ee-8d87-4c59-8e18-e6b166b6d2cd.json
  content/taxonomy_term/e6f319ee-8d87-4c59-8e18-e6b166b6d2cd.yml
  content/taxonomy_term/ec1ed532-edc7-464f-ba09-26958a42d8d0.json
  content/taxonomy_term/ec1ed532-edc7-464f-ba09-26958a42d8d0.yml
  content/taxonomy_term/f9979993-225b-4bdb-906f-daa2626332c5.json
  content/taxonomy_term/f9979993-225b-4bdb-906f-daa2626332c5.yml
  stanford_events.info.yml
Labels: patch, size/l

#41 D8CORE-2967: fixing the past event label to work with articles without type
  dist/css/stanford_events.node.css
  dist/js/stanford_events.node.behaviors.js
  lib/js/stanford_events.behavior.js
  lib/scss/stanford_events.node.scss
Labels: size/xs

#44 D8CORE-2325: Added separator for date field.
  config/install/core.entity_view_display.node.stanford_event.default.yml
Labels: size/xs
