Repository SU-SWS/stanford_events, pull requests merged in 2020-07, with the labels that each got.

#15 D8CORE-2290: moving the CTA button in the events node page.
  config/install/core.entity_view_display.node.stanford_event.default.yml
  dist/css/stanford_events.node.css
  lib/scss/stanford_events.node.scss
  stanford_events.layouts.yml
  templates/sections/event-body-two-column.html.twig
Labels: size/xs

#13 D8CORE-2223: Add smart_date patch to prevent duplicate timezones.
  composer.json
  modules/stanford_events_importer/config/install/ultimate_cron.job.stanford_migrate_stanford_events_importer.yml
  modules/stanford_events_importer/stanford_events_importer.info.yml
  tests/codeception/acceptance/StanfordEventsCest.php
  tests/codeception/acceptance/StanfordEventsImporterCest.php
Labels: patch, size/xs

#12 D8CORE-2218: Patched DS for empty grouping title.
  composer.json
Labels: size/xs

#10 D8CORE-2228: adding in the nav region with the correct names
  templates/block/block--menu-block--stanford-event-types.html.twig
Labels: size/xs

#14 D8CORE-2318: removing the link action. list items shouldn't have it
  config/install/views.view.stanford_events.yml
  templates/components/event-schedule/event-schedule.html.twig
  templates/components/events-list/events-list.html.twig
Labels: size/xs

#16 D8CORE-2319: changed the padding on the list items to MS 4 like news
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.views.scss
Labels: size/xs

#17 D8CORE-2317: fix to the missing location on events
  config/install/views.view.stanford_events.yml
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.views.scss
  modules/stanford_events_series/config/install/views.view.stanford_event_series.yml
  package-lock.json
  templates/components/events-explore-more/events-explore-more.html.twig
  templates/components/events-list/events-list.html.twig
  templates/components/events-list/events-list.ui_patterns.yml
Labels: size/l

#19 Release 8.1.1
  CHANGELOG.md
  composer.json
  config/install/core.entity_view_display.node.stanford_event.default.yml
  config/install/views.view.stanford_events.yml
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.node.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.node.scss
  lib/scss/stanford_events.views.scss
  modules/stanford_events_importer/config/install/ultimate_cron.job.stanford_migrate_stanford_events_importer.yml
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/config/install/views.view.stanford_event_series.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  package-lock.json
  stanford_events.info.yml
  stanford_events.layouts.yml
  templates/block/block--menu-block--stanford-event-types.html.twig
  templates/components/event-schedule/event-schedule.html.twig
  templates/components/events-explore-more/events-explore-more.html.twig
  templates/components/events-list/events-list.html.twig
  templates/components/events-list/events-list.ui_patterns.yml
  templates/sections/event-body-two-column.html.twig
  tests/codeception/acceptance/StanfordEventsCest.php
  tests/codeception/acceptance/StanfordEventsImporterCest.php
Labels: patch, size/l

#20 Removed views_taxonomy_term_name_depth thats not used
  composer.json
Labels: size/xs

#21 DEVOPS-000: https://www.drupal.org/project/ds/issues/3154727 Patch merged in
  composer.json
Labels: size/xs
