Repository SU-SWS/stanford_events, pull requests merged in 2021-02, with the labels that each got.

#51 D8CORE-3451: fixing the date aligment for events on lists
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.node.css
  dist/css/stanford_events.views.css
  lib/scss/stanford_events.views.scss
  package-lock.json
  package.json
Labels: size/l

#50 D8CORE-2968: Fix for deleted schedule items still appearing
  composer.json
  config/install/core.entity_view_display.node.stanford_event.default.yml
  config/install/views.view.stanford_events.yml
  tests/codeception/functional/StanfordEventsScheduleCest.php
Labels: size/xl

#52 "8.x-1.x 8.1.7
  .circleci/config.yml
  CHANGELOG.md
  composer.json
  config/install/core.entity_view_display.node.stanford_event.default.yml
  config/install/views.view.stanford_events.yml
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.node.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.node.scss
  lib/scss/stanford_events.views.scss
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  package-lock.json
  package.json
  stanford_events.info.yml
  tests/codeception/acceptance/StanfordEventsImporterCest.php
  tests/codeception/acceptance/StanfordEventsSeriesCest.php
  tests/codeception/functional/StanfordEventsScheduleCest.php
Labels: patch, size/xl

#53 Updated views taxonomy term name depth patch
  composer.json
Labels: size/xs

#55 "8.x-1.x 8.1.8
  CHANGELOG.md
  composer.json
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
Labels: patch, size/xs

#56 Move patches to shared package
  composer.json
  stanford_events.info.yml
Labels: size/xs
