Repository SU-SWS/stanford_events, pull requests merged in 2021-05, with the labels that each got.

#69 "8.x-1.x 8.1.13
  CHANGELOG.md
  dist/css/stanford_events.event-card.css
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.event-schedule.css
  dist/css/stanford_events.node.css
  dist/css/stanford_events.views.css
  dist/js/stanford_events.node.behaviors.js
  lib/js/stanford_events.behavior.js
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/components/event-schedule/stanford_events.event-schedule.scss
  lib/scss/stanford_events.node.scss
  lib/scss/stanford_events.views.scss
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
  templates/components/event-schedule/event-schedule.html.twig
  templates/components/person-cta/person-cta.html.twig
Labels: patch, size/xs

#70 D8CORE-2520 Refactored templates and use full month for screen readers
  config/install/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/install/core.entity_view_display.node.stanford_event.teaser.yml
  config/install/core.entity_view_display.paragraph.stanford_person_cta.default.yml
  config/install/core.entity_view_display.paragraph.stanford_schedule.default.yml
  config/install/views.view.stanford_events.yml
  config/install/views.view.stanford_events_past.yml
  modules/stanford_events_series/config/install/views.view.stanford_event_series.yml
  stanford_events.module
  templates/components/card/card.html.twig
  templates/components/card/card.ui_patterns.yml
  templates/components/events-card/events-card.html.twig
  templates/components/events-explore-more/events-explore-more.html.twig
  templates/components/events-explore-more/events-explore-more.ui_patterns.yml
  templates/components/events-list/events-list.html.twig
  templates/components/list/list.html.twig
  templates/components/list/list.ui_patterns.yml
  templates/components/person-cta/person-cta.ui_patterns.yml
  templates/components/schedule/schedule.html.twig
  templates/components/schedule/schedule.ui_patterns.yml
  tests/codeception/acceptance/StanfordEventsCest.php
Labels: size/m

#72 D8CORE-3162: Changing the headline text size for events in cards and lists
  dist/css/stanford_events.event-card.css
  dist/css/stanford_events.event-list.css
  lib/scss/components/event-card/stanford_events.event-card.scss
  lib/scss/components/event-list/stanford_events.event-list.scss
Labels: size/xs
