Repository SU-SWS/stanford_events, pull requests merged in 2021-03, with the labels that each got.

#54 D8CORE-3463 Adjust the list and cards displays
  config/install/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/install/views.view.stanford_events.yml
  dist/css/stanford_events.event-card.css
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-card/_event-card--heading-link.scss
  lib/scss/components/event-card/_event-card--item-type-link.scss
  lib/scss/components/event-card/_event-spacing-explore-more--card.scss
  lib/scss/components/event-card/_event-stacked-date--card.scss
  lib/scss/components/event-card/stanford_events.event-card.scss
  lib/scss/components/event-list/_event-date-time-icons.scss
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.views.scss
  modules/stanford_events_series/dist/css/stanford_events_series.node.css
  modules/stanford_events_series/lib/scss/stanford_events_series.node.scss
  stanford_events.libraries.yml
  templates/components/events-card/events-card.ui_patterns.yml
  templates/components/events-explore-more/events-explore-more.html.twig
  templates/components/events-explore-more/events-explore-more.ui_patterns.yml
Labels: patch, size/xl

#58 D8CORE-3352: styles for past events page
  dist/css/stanford_events.event-list.css
  lib/scss/components/event-list/stanford_events.event-list.scss
Labels: size/xs

#60 "8.x-1.x 8.1.9
  CHANGELOG.md
  composer.json
  config/install/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/install/views.view.stanford_events.yml
  dist/css/stanford_events.event-card.css
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-card/_event-card--heading-link.scss
  lib/scss/components/event-card/_event-card--item-type-link.scss
  lib/scss/components/event-card/_event-spacing-explore-more--card.scss
  lib/scss/components/event-card/_event-stacked-date--card.scss
  lib/scss/components/event-card/stanford_events.event-card.scss
  lib/scss/components/event-list/_event-date-time-icons.scss
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.views.scss
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/dist/css/stanford_events_series.node.css
  modules/stanford_events_series/lib/scss/stanford_events_series.node.scss
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
  stanford_events.libraries.yml
  templates/components/events-card/events-card.ui_patterns.yml
  templates/components/events-explore-more/events-explore-more.html.twig
  templates/components/events-explore-more/events-explore-more.ui_patterns.yml
Labels: patch, size/xl

#61 8.1.10
  CHANGELOG.md
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
  templates/components/event-schedule/event-schedule.html.twig
  templates/components/events-explore-more/events-explore-more.html.twig
  templates/components/events-list/events-list.html.twig
  templates/components/person-cta/person-cta.html.twig
Labels: patch

#63 D8CORE-3957: setting the events cards to be one per row at the med br…
  CHANGELOG.md
  dist/css/stanford_events.event-card.css
  lib/scss/components/event-card/stanford_events.event-card.scss
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
Labels: patch, size/xs

#62 D8CORE-3938: styling the subhead on the list of events
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.views.scss
Labels: size/xs
