Repository SU-SWS/stanford_events, pull requests merged in 2021-04, with the labels that each got.

#64 D8CORE-4033: updated view config with past events filters
  config/install/views.view.stanford_events.yml
Labels: size/l

#65 "8.x-1.x 8.1.12
  CHANGELOG.md
  config/install/views.view.stanford_events.yml
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.views.scss
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
Labels: patch, size/l

#66 D8CORE-3950: correcting the title spacing
  dist/css/stanford_events.event-list.css
  dist/css/stanford_events.views.css
  lib/scss/components/event-list/stanford_events.event-list.scss
  lib/scss/stanford_events.views.scss
Labels: size/xs
