Repository SU-SWS/stanford_events, pull requests merged in 2021-06, with the labels that each got.

#71 D8CORE-4173: changed from padding to margin to fix up the event cards
  dist/css/stanford_events.event-card.css
  lib/scss/components/event-card/stanford_events.event-card.scss
Labels: size/xs

#73 "8.x-1.x 8.1.14
  .circleci/config.yml
  .github/pull_request_template.md
  CHANGELOG.md
  composer.json
  config/install/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/install/core.entity_view_display.node.stanford_event.teaser.yml
  config/install/core.entity_view_display.paragraph.stanford_person_cta.default.yml
  config/install/core.entity_view_display.paragraph.stanford_schedule.default.yml
  config/install/views.view.stanford_events.yml
  config/install/views.view.stanford_events_past.yml
  dist/css/stanford_events.event-card.css
  dist/css/stanford_events.event-list.css
  lib/scss/components/event-card/stanford_events.event-card.scss
  lib/scss/components/event-list/stanford_events.event-list.scss
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/config/install/views.view.stanford_event_series.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
  stanford_events.module
  templates/components/card/card.html.twig
  templates/components/card/card.ui_patterns.yml
  templates/components/events-card/events-card.html.twig
  templates/components/events-explore-more/events-explore-more.html.twig
  templates/components/events-explore-more/events-explore-more.ui_patterns.yml
  templates/components/events-list/events-list.html.twig
  templates/components/list/list.html.twig
  templates/components/list/list.ui_patterns.yml
  templates/components/person-cta/person-cta.ui_patterns.yml
  templates/components/schedule/schedule.html.twig
  templates/components/schedule/schedule.ui_patterns.yml
  tests/codeception/acceptance/StanfordEventsCest.php
Labels: patch, size/l

#74 8.1.15
  CHANGELOG.md
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
  templates/components/card/card.html.twig
Labels: patch, size/xs

#75 D8CORE-4378: fixing the skip to secondary nav link
  templates/block/block--menu-block--stanford-event-types.html.twig
Labels: patch, size/xs

#76 D8CORE-4236: fixing the event date alignment on cards and lists of card or default list
  dist/css/stanford_events.event-card.css
  dist/css/stanford_events.event-list.css
  lib/scss/components/event-card/_event-stacked-date--card.scss
  lib/scss/components/event-card/stanford_events.event-card.scss
Labels: size/xs
