Repository SU-SWS/stanford_events, pull requests merged in 2022-05, with the labels that each got.

#111 Updated dev dependencies
  composer.json
Labels: size/xs

#112 8.1.26
  CHANGELOG.md
  composer.json
  dist/css/stanford_events.event-filter-menu.css
  dist/css/stanford_events.event-list.css
  lib/scss/components/event-filter-menu/stanford_events.event-filter-menu.scss
  lib/scss/components/event-list/stanford_events.event-list.scss
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  pdb_components/mini-calendar/build/asset-manifest.json
  pdb_components/mini-calendar/build/static/css/main.css
  pdb_components/mini-calendar/build/static/js/main.js
  pdb_components/mini-calendar/package.json
  pdb_components/mini-calendar/src/components/EventCard.js
  pdb_components/mini-calendar/src/components/NavigationButton.js
  pdb_components/mini-calendar/src/index.js
  pdb_components/mini-calendar/src/styles.scss
  pdb_components/mini-calendar/yarn.lock
  stanford_events.info.yml
Labels: size/s, patch

#113 8.1.27
  CHANGELOG.md
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_importer/stanford_events_importer.module
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
Labels: patch

#114 8.1.28
  CHANGELOG.md
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_importer/stanford_events_importer.module
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
Labels: patch

#115 8.1.29
  CHANGELOG.md
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  pdb_components/mini-calendar/build/asset-manifest.json
  pdb_components/mini-calendar/build/static/js/main.js
  pdb_components/mini-calendar/src/index.js
  stanford_events.info.yml
Labels: size/xs, patch

#116 D8CORE-5684: adding additional visual cues
  pdb_components/mini-calendar/build/static/css/main.css
  pdb_components/mini-calendar/src/styles.scss
Labels: size/xs
