Repository SU-SWS/stanford_events, pull requests merged in 2022-03, with the labels that each got.

#102 8.1.22
  CHANGELOG.md
  composer.json
  config/install/smart_date.smart_date_format.stanford_events_long.yml
  config/install/smart_date.smart_date_format.time_only_no_all_day.yml
  dist/css/stanford_events.event-list.css
  lib/scss/components/event-list/stanford_events.event-list.scss
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  package.json
  stanford_events.info.yml
  templates/components/list/list.html.twig
Labels: size/xs, patch

#100 test on php8
  .circleci/config.yml
Labels: size/xs

#101 D8CORE-5102 Events mini-calendar using PDB
  pdb_components/mini-calendar/.env
  pdb_components/mini-calendar/.nvmrc
  pdb_components/mini-calendar/build/asset-manifest.json
  pdb_components/mini-calendar/build/index.html
  pdb_components/mini-calendar/build/static/css/main.css
  pdb_components/mini-calendar/build/static/js/main.js
  pdb_components/mini-calendar/build/static/js/main.js.LICENSE.txt
  pdb_components/mini-calendar/mini_calendar.info.yml
  pdb_components/mini-calendar/package-lock.json
  pdb_components/mini-calendar/package.json
  pdb_components/mini-calendar/public/index.html
  pdb_components/mini-calendar/src/index.js
  pdb_components/mini-calendar/src/styles.scss
  pdb_components/mini-calendar/yarn.lock
Labels: size/xl, patch

#103 update views infinite scroll
  composer.json
Labels: size/xs

#104 8.1.23
  .circleci/config.yml
  CHANGELOG.md
  composer.json
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  pdb_components/mini-calendar/.env
  pdb_components/mini-calendar/.nvmrc
  pdb_components/mini-calendar/build/asset-manifest.json
  pdb_components/mini-calendar/build/index.html
  pdb_components/mini-calendar/build/static/css/main.css
  pdb_components/mini-calendar/build/static/js/main.js
  pdb_components/mini-calendar/build/static/js/main.js.LICENSE.txt
  pdb_components/mini-calendar/mini_calendar.info.yml
  pdb_components/mini-calendar/package-lock.json
  pdb_components/mini-calendar/package.json
  pdb_components/mini-calendar/public/index.html
  pdb_components/mini-calendar/src/index.js
  pdb_components/mini-calendar/src/styles.scss
  pdb_components/mini-calendar/yarn.lock
  stanford_events.info.yml
Labels: size/xl, patch

#106 8.1.24
  CHANGELOG.md
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  pdb_components/mini-calendar/build/static/css/main.css
  pdb_components/mini-calendar/src/styles.scss
  stanford_events.info.yml
Labels: patch
