Repository SU-SWS/stanford_events, pull requests merged in 2022-01, with the labels that each got.

#90 Added localist URL to external source field.
  modules/stanford_events_importer/config/install/migrate_plus.migration.stanford_localist_importer.yml
Labels: size/xs

#91 8.1.19
  CHANGELOG.md
  README.md
  config/install/node.type.stanford_event.yml
  modules/stanford_events_importer/config/install/core.entity_form_display.config_pages.stanford_events_importer.default.yml
  modules/stanford_events_importer/src/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidget.php
  modules/stanford_events_importer/src/StanfordEventsImporter.php
  modules/stanford_events_importer/stanford_events_importer.install
  modules/stanford_events_importer/tests/src/Kernel/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidgetTest.php
  modules/stanford_events_importer/tests/src/Unit/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidgetTest.php
  modules/stanford_events_importer/tests/src/Unit/StanfordEventsImporterTest.php
  stanford_events.info.yml
  tests/codeception/acceptance/StanfordEventsCest.php
Labels: size/s, patch

#93 8.1.19
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_importer/stanford_events_importer.install
Labels: size/xs, patch

#92 D8CORE-5000: Constraining the components to the 10-of-12 col width
  modules/stanford_events_series/config/install/core.entity_view_display.node.stanford_event_series.default.yml
Labels: size/xs

#94 8.1.21
  CHANGELOG.md
  modules/stanford_events_importer/config/install/migrate_plus.migration.stanford_localist_importer.yml
  modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events_series/config/install/core.entity_view_display.node.stanford_event_series.default.yml
  modules/stanford_events_series/stanford_events_series.info.yml
  stanford_events.info.yml
Labels: size/xs, patch
